---
title: "Figure 3"
author: "Sahil Shah"
date: "8/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(viridis)
library(grid)
library(gridExtra)
library(cowplot)
library(reshape2)
```

Creates dataframe of each normalized RMSE values for each subpattern simulated x number of times.
```{r}

setwd("../../results/")

pattern <- c()
nrmse <- c()
best_patterns <- c()
tmp_avg <- 5.0

#Goes into each directory and finds the corresponding folders to extract normalized RMSE data for each subpattern ran
for(data in 1:66){
  data_name <- paste0("paper_data", data)
  pattern_name <- as.character(data)
  for(day in 13:26){
    date <- paste0("2020_8_", day)
    for(rep in 1:20){
      if(dir.exists(paste0("./", date, "/", data_name, "_rep", rep, "_nmut10/final/"))){
        rmse_data <- read.table(paste0("./", date, "/", data_name, "_rep", rep, "_nmut10/final/rmse_data.tsv"), header=TRUE)
        rmse_data <- rmse_data %>% filter(Accepted=='yes')
        min_rmse <- rmse_data$NRMSE[rmse_data$NRMSE == min(rmse_data$NRMSE)]
        pattern[length(pattern) + 1] <- pattern_name
        nrmse[length(nrmse) + 1] <- min_rmse
      }
      else{
        break
      }
    }
  }
}

df <- data.frame(pattern, nrmse)

```

Determines the best subpattern for a set and removes all others from dataframe.
```{r}

index <- 1

#If the mean is lower than the previous subplot then it is retained in the dataframe
for(data in 1:60){
  if(mean(df[df$pattern==as.character(data),]$nrmse) < tmp_avg){
    best_patterns[index] <- as.character(data)
    tmp_avg <- mean(df[df$pattern==as.character(data),]$nrmse)
  }
  #Once entire "pattern" has been sorted through, move on to the next "pattern"
  if(data %% 6 == 0){
    tmp_avg <- 5.0
    index <- index + 1
  }
}

#Reorganize the data so that they can be plotted in desired order
df <- df %>% filter(pattern %in% best_patterns)
df$pattern <- factor(df$pattern,levels = unique(df$pattern))

```

Creates boxplot of the normalized RMSE values per pattern.
```{r}

nrmse_bp <- df %>% ggplot(aes(x=pattern, y=nrmse)) + 
  geom_boxplot(lwd=3) + 
  geom_jitter(color="black", size=7.0, alpha=1.0) + 
  theme(legend.position="none",
        plot.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.margin = unit(c(8,1,1,1), "cm"), 
        axis.text.x = element_text(size=130), 
        axis.text.y = element_text(size=130), 
        axis.line = element_line(size=2.3), 
        axis.ticks = element_line(size=2.3), 
        axis.ticks.length = unit(1.0, "cm"),
        axis.title = element_text(size=125)) +
  xlab("Pattern") +
  ylab("Normalized RMSE") +
  scale_y_continuous(limits=c(0, 0.35), expand=c(0,0)) +
  scale_x_discrete(labels=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"))

#Letter corresponding to plot in figure is added
nrmse_bp <- arrangeGrob(nrmse_bp, top=textGrob("B", x = unit(0, "npc"), y=unit(-0.2, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=180, fontfamily="Arial")))
```

Creates plots for each pattern to display on the top of the figure.
```{r}

plots <- list()
starting <- 1

#Reads in tsv files containing transcript abundances
for(dat in seq(1, 60, 6)){
  target_data <- read.table(paste0("../../data/targets/paper_data", dat, ".tsv"), header=TRUE)
  target_data <- filter(target_data, species == "protein1" | species == "protein2" | species == "protein3")
  #Plots each pattern and modifies based on position of plot in outputted figure
  if(starting == 1){
    target_line_plot <-  ggplot(target_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
      geom_line(stat="identity", size=2) + 
      theme(panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            plot.margin = unit(c(1,1.5,1,1), "cm"), 
            axis.line.x = element_blank(), 
            axis.line.y = element_line(size=2.3), 
            axis.ticks.x = element_blank(), 
            axis.ticks.y = element_line(size=2.3), 
            axis.text.x = element_blank(), 
            axis.text.y = element_text(size=130), 
            axis.ticks.length.y = unit(1.0, "cm"),
            axis.title.x = element_blank(), 
            axis.title.y = element_text(size=125),
            legend.position = "none") + 
      scale_color_manual(values=c("#000000", "#000000", "#000000")) +
      panel_border(size=1, color="grey") +
      scale_y_continuous(limits = c(0, 45), expand = c(0, 0)) +
      ylab("Transcript abundance")
  }else if(starting == 6){
    target_line_plot <-  ggplot(target_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
      geom_line(stat="identity", size=2) + 
      theme(panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            plot.margin = unit(c(1,1.5,1,1), "cm"), 
            axis.line = element_line(size=2.3), 
            axis.ticks = element_line(size=2.3), 
            axis.text = element_text(size=130), 
            axis.ticks.length = unit(1.0, "cm"),
            axis.title.x = element_text(size=125),
            axis.title.y = element_text(size=125),
            legend.position = "none") + 
      scale_color_manual(values=c("#000000", "#000000", "#000000")) + 
      panel_border(size=1, color="grey") + 
      scale_y_continuous(limits = c(0, 45), expand = c(0, 0)) +
      ylab("Transcript abundance") +
      xlab("Time (s)")
  }else if(starting <= 5){
    target_line_plot <-  ggplot(target_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
      geom_line(stat="identity", size=2) + 
      theme(panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            plot.margin = unit(c(1,1,1,1.5), "cm"), 
            axis.line = element_blank(),
            axis.ticks = element_blank(), 
            axis.text = element_blank(), 
            axis.ticks.length.x = unit(1.0, "cm"),
            axis.title = element_blank(),
            legend.position = "none") + 
      scale_color_manual(values=c("#000000", "#000000", "#000000")) + 
      panel_border(size=1, color="grey") + 
      scale_y_continuous(limits = c(0, 45), expand = c(0, 0))
  }else{
    target_line_plot <-  ggplot(target_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
      geom_line(stat="identity", size=2) + 
      theme(panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            plot.margin = unit(c(1,1,1,1.5), "cm"), 
            axis.line.y = element_blank(),
            axis.ticks.y = element_blank(), 
            axis.text.y = element_blank(), 
            axis.line.x = element_line(size=2.3),
            axis.ticks.x = element_line(size=2.3), 
            axis.text.x = element_text(size=130), 
            axis.ticks.length.x = unit(1.0, "cm"),
            axis.title.y = element_blank(),
            axis.title.x = element_text(size=125),
            legend.position = "none") + 
      scale_color_manual(values=c("#000000", "#000000", "#000000")) + 
      panel_border(size=1, color="grey") + 
      scale_y_continuous(limits = c(0, 45), expand = c(0, 0)) +
      xlab("Time (s)")
  }
  plots[[starting]] <- target_line_plot
  starting <- starting + 1
}

#Labels plots with its corresponding lettering
for(i in 1:length(plots)){
  if(i == 1){
    plots[[i]] <- arrangeGrob(plots[[i]], top=textGrob("A", x = unit(0, "npc"), y=unit(0.7, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=180, fontfamily="Arial")))
  }else if(i <= 5){
    plots[[i]] <- arrangeGrob(plots[[i]], top=textGrob("A", x = unit(0, "npc"), y=unit(0.5, "npc"), just=c("left","top"), gp=gpar(col="white", font="bold", fontsize=180, fontfamily="Arial")))
  }else{
    plots[[i]] <- arrangeGrob(plots[[i]], top=textGrob("A", x = unit(0, "npc"), y=unit(0, "npc"), just=c("left","top"), gp=gpar(col="white", font="bold", fontsize=180, fontfamily="Arial")))
  }

}

```

Create figure and save.
```{r}

figure3 <- grid.arrange(plots[[1]], plots[[2]], plots[[3]], plots[[4]], plots[[5]], plots[[6]], plots[[7]], plots[[8]], plots[[9]], plots[[10]], nrmse_bp, layout_matrix=rbind(c(1,2,3,4,5), c(6,7,8,9,10), c(11)), widths=c(2.6,2.2,2.2,2.2,2.2))
ggsave("../../data/figures/figure3/figure3.png", figure3, height=80, width=150, limitsize=FALSE, dpi=72)

```

