---
title: "Figure 1"
author: "Sahil Shah"
date: "4/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cowplot)
library(dplyr)
library(gridExtra)
library(ggplot2)
library(grid)
library(reshape2)
library(gtools)
library(png)
```

Produce target data plot

```{r, echo=FALSE}

#Set working directory to the directory in which the target data is contained in 
setwd("../../data/")

#Change grant_data name to the target file used
target_data <- read.table("positive_control3.tsv", header=TRUE)
target_data <- filter(target_data, species == "protein1" | species == "protein2" | species == "protein3")

#Create plot
target_line_plot <-  ggplot(target_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
  geom_line(stat="identity", size=2) + 
  ggtitle("Target pattern") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_rect(color='#DCDCDC'), 
        plot.margin = unit(c(0.5,1,0.5,1), "cm"), 
        axis.line = element_line(size=1.3), 
        axis.ticks = element_line(size=1.3), 
        axis.text.x = element_text(size=39), 
        axis.text.y = element_text(size=39), 
        axis.ticks.length = unit(0.4, "cm"),
        axis.title = element_text(size=39), 
        plot.title = element_text(color="black", hjust=0.5, size=39), 
        legend.position = "none") + 
  xlab("Time (s)") + 
  ylab("Transcript abundance") + 
  scale_color_manual(values=c("#56B4E9", "#E69F00", "#CC79A7")) + 
  panel_border() + 
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0)) +
  theme(plot.title = element_text(vjust=20))

```

Produce generation 0 plot

```{r, echo=FALSE}

#Set working directory to the directory in which the template genome data is contained in 
setwd("../../results/2020_7_2/positive_control3_rep1_nmut20/")

#List all transcript output files
best_files <- list.files(pattern="expression_pattern_")
plot_data <- read.table(best_files[1], header=TRUE)
plot_data <- filter(plot_data, species == "protein1" | species == "protein2" | species == "protein3")

#Create plot
line_plot_zero <-  ggplot(plot_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
  geom_line(stat="identity", size=2) + 
  ggtitle("Generation 0") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        plot.margin=unit(c(0.5,1,0.5,1), "cm"), 
        axis.text.x = element_text(size=39), 
        axis.text.y = element_blank(), 
        axis.line.x = element_line(size=1.3), 
        axis.line.y = element_blank(), 
        axis.ticks.x = element_line(size=1.3),
        axis.ticks.y = element_blank(), 
        axis.ticks.length.x = unit(0.4, "cm"),
        axis.title.x = element_text(size=39), 
        axis.title.y = element_blank(),
        plot.title = element_text(color="black", hjust=0.5, size=39), 
        legend.position = "none") + 
  xlab("Time (s)") + 
  scale_color_manual(values=c("#56B4E9", "#E69F00", "#CC79A7")) + 
  panel_border() +
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0)) +
  theme(plot.title = element_text(vjust=20))

```

Produce generation 1 plot
```{r, echo=FALSE}

#Set working directory to the directory in which the first output data is contained in 
setwd("../../results/2020_7_2/positive_control3_rep1_nmut20/")

#List all transcript output files
best_files <- list.files(pattern="expression_pattern_")
plot_data <- read.table(best_files[20], header=TRUE)
plot_data <- filter(plot_data, species == "protein1" | species == "protein2" | species == "protein3")

#Create plot
line_plot_int <-  ggplot(plot_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
  geom_line(stat="identity", size=2) + 
  ggtitle("Generation 766") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        plot.margin = unit(c(0.5,1,0.5,1), "cm"), 
        axis.text.x = element_text(size=39), 
        axis.text.y = element_blank(), 
        axis.line.x = element_line(size=1.3), 
        axis.line.y = element_blank(), 
        axis.ticks.x = element_line(size=1.3),
        axis.ticks.y = element_blank(), 
        axis.ticks.length.x = unit(0.4, "cm"),
        axis.title.x = element_text(size=39), 
        axis.title.y = element_blank(),
        plot.title = element_text(color="black", hjust=0.5, size=39), 
        legend.position = "none") + 
  xlab("Time (s)") + 
  scale_color_manual(values=c("#56B4E9", "#E69F00", "#CC79A7")) + 
  panel_border() + 
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0)) +
  theme(plot.title = element_text(vjust=20))

```
Produce final generation plot
```{r, echo=FALSE}

#Set working directory to the directory in which the first output data is contained in 
setwd("../../results/2020_7_2/positive_control3_rep1_nmut20/final/")

#List all transcript output files
plot_data <- read.table('expression_pattern_best.tsv', header=TRUE)
plot_data <- filter(plot_data, species == "protein1" | species == "protein2" | species == "protein3")

#Create plot
line_plot_final <-  ggplot(plot_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) +
  geom_line(stat="identity", size=2) + 
  ggtitle("Final pattern") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        plot.margin = unit(c(0.5,1,0.5,1), "cm"), 
        axis.text.x = element_text(size=39), 
        axis.text.y = element_blank(),
        axis.line.x = element_line(size=1.3), 
        axis.line.y = element_blank(), 
        axis.ticks.x = element_line(size=1.3),
        axis.ticks.y = element_blank(), 
        axis.ticks.length.x = unit(0.4, "cm"),
        axis.title.x = element_text(size=39), 
        axis.title.y = element_blank(),
        plot.title = element_text(color="black", hjust=0.5, size=39), 
        legend.position = "none") + 
  xlab("Time (s)") + 
  scale_color_manual(values=c("#56B4E9", "#E69F00", "#CC79A7")) + 
  panel_border() + 
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0)) +
  theme(plot.title = element_text(vjust=20))
```
Produce fitness over time plot
```{r, echo=FALSE}

#Set working directory to the directory in which the results are contained in
setwd("../../results/2020_7_2/positive_control3_rep1_nmut20/final/")

#Filter sum of squares data
all_rmse_data <- read.table("rmse_data.tsv", header=TRUE)
rmse_data_acc <- all_rmse_data %>% filter(Accepted=='yes')

#Create sum of squares plot
rmse_line_plot <- ggplot(rmse_data_acc, aes(x=Iteration, y=NRMSE)) + 
  geom_point(stat='identity', color='#D55E00', size=3) + 
  geom_line(size=2, stat='identity', color='#D55E00') + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        plot.margin = unit(c(1.8,1,1,1), "cm"), 
        axis.text.x = element_text(size=39), 
        axis.text.y = element_text(size=39), 
        axis.line = element_line(size=1.3), 
        axis.ticks = element_line(size=1.3), 
        axis.ticks.length = unit(0.3, "cm"),
        axis.title = element_text(size=35),
        legend.position = "none") +
  xlab("Generation") + 
  ylab("Root mean square error") + 
  panel_border() +

rmse_line_plot <- arrangeGrob(rmse_line_plot, top=textGrob("B", x = unit(0, "npc"), y=unit(1, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=60, fontfamily="Arial")))

```
Make figure 1
```{r}

setwd("../../data/figures/figure1/")

#Read in genome architectures
img1 <- readPNG("figure1_beg_genome_arch.png")
img1 <- arrangeGrob(rasterGrob(img1, vjust=3.18, width=0.95, hjust=0.45), top=textGrob("A", x = unit(0, "npc"), y=unit(-7.5, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=60, fontfamily="Arial")))
img2 <- readPNG("figure1_gen0_genome_arch.png")
img3 <- readPNG("figure1_intermed_genome_arch.png")
img4 <- readPNG("figure1_final_genome_arch.png")

#Create and save Figure 1
figure1 <- grid.arrange(img1, rasterGrob(img2, vjust=3.5, width=0.98), rasterGrob(img3, vjust=3.86, width=0.98), rasterGrob(img4, vjust=3.68, width=0.99), target_line_plot, line_plot_zero, line_plot_int, line_plot_final, rmse_line_plot, layout_matrix=rbind(c(1,2,3,4), c(5,6,7,8), c(9,9,9,9)), widths=c(2.3,2,2,2))

ggsave("figure1.png", figure1, height=25, width=40)

```
