---
title: "Beta landscape"
author: "Sahil Shah"
date: "8/27/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(grid)
library(gridExtra)
library(cowplot)
```

Determines the beta values over each generation
```{r}

#Set the values for the x and y-axes
generations <- c(1:5000)

slope1 <- (1.1 - 1e-2) / (0.8 * 5000)
beta_val1 <- (slope1 * (generations[501:4500] - 500)) + 1e-2

slope2 <- (1.3 - 1.1) / (0.1 * 5000)
beta_val2 <- (slope2 * (generations[4501:5000] - 4500)) + 1.1

beta <- c(rep(0.01, 500), beta_val1, beta_val2)

```

Plots the beta values over each generation and saves it
```{r}

fitness_landscape <- data.frame(generations, beta)
beta_plot <- fitness_landscape %>% ggplot(aes(x=generations, y=beta)) + 
  geom_line(size=2, stat='identity', color='#000000') + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        plot.margin = unit(c(1.8,1,1,1), "cm"), 
        axis.text.x = element_text(size=39), 
        axis.text.y = element_text(size=39), 
        axis.line = element_line(size=1.3), 
        axis.ticks = element_line(size=1.3), 
        axis.ticks.length = unit(0.3, "cm"),
        axis.title = element_text(size=40),
        legend.position = "none",
        plot.title = element_text(size=45, face='bold')) +
  ggtitle("Beta value over generations") +
  xlab("Generation") + 
  ylab("Beta value") + 
  panel_border(size=1, color="grey") +
  scale_y_log10()

ggsave("../../manuscript_figures/si_figures/beta.png", beta_plot, height=15, width=30)

```

