---
title: "Figure 3 Pre-Processing"
author: "Sahil Shah"
date: "12/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}

library(dplyr)
library(ggplot2)
library(viridis)
library(grid)
library(gridExtra)
library(cowplot)
library(reshape2)
```

Creates dataframe of each normalized RMSE values for each subpattern simulated x number of times.

```{r}

setwd("../../results/figs_3_and_4/")

pattern <- c()
nrmse <- c()
best_patterns <- c()
tmp_avg <- 5.0

#Goes into each directory and finds the corresponding folders to extract normalized RMSE data for each subpattern ran
for(data in 1:10){
  for(arrangement in 1:6){
    data_name <- paste0("paper_data", data, "_arrange", arrangement)
    pattern_name <- as.character(paste0(data,arrangement))
    for(rep in 1:50){
      if(dir.exists(paste0("./", data_name, "/rep", rep, "/final/"))){
        rmse_data <- read.table(paste0("./", data_name, "/rep", rep, "/final/rmse_data.tsv"), header=TRUE)
        rmse_data <- rmse_data %>% filter(Accepted=='yes')
        min_rmse <- rmse_data$NRMSE[rmse_data$NRMSE == min(rmse_data$NRMSE)]
        pattern[length(pattern) + 1] <- pattern_name
        nrmse[length(nrmse) + 1] <- min_rmse
      }
    }
  }
}

df <- data.frame(pattern, nrmse)

```

Determines the best subpattern for a set and removes all others from dataframe.

```{r}

index <- 1

#If the mean is lower than the previous subplot then it is retained in the dataframe
for(data in 1:10){
  for(arrangement in 1:6){
    if(mean(df[df$pattern==as.character(paste0(data,arrangement)),]$nrmse) < tmp_avg){
      best_patterns[index] <- as.character(paste0(data,arrangement))
      tmp_avg <- mean(df[df$pattern==as.character(paste0(data,arrangement)),]$nrmse)
    }
  }
  #Once entire "pattern" has been sorted through, move on to the next "pattern"
  tmp_avg <- 5.0
  index <- index + 1
}

#Reorganize the data so that they can be plotted in desired order
df <- df %>% filter(pattern %in% best_patterns)
df$pattern <- factor(df$pattern,levels = c(15,26,32,43,51,61,73,82,94,104))

```

Output CSV file containing the best gene arrangements and their respective nRMSE values.

```{r}

write.csv(df, file="../../results/figure3_data.csv", row.names=FALSE)

```
