---
title: "Figure 5"
author: "Sahil Shah"
date: "10/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cowplot)
library(dplyr)
library(ggplot2)
library(ggsci)
library(grid)
library(gridExtra)
library(png)

color_palette <- c("#00468BFF", "#42B540FF", "#0099B4FF", "#925E9FFF", "#FDAF91FF", "#AD002AFF", "#ADB6B6FF", "#1B1919FF", "#ED0000FF", "#024B30")

```

Create 10 gene target plot.

```{r}

setwd("../../../data/targets/")

#Read in target tsv file and filter for only proteins
target_data <- read.table("ten_genes.tsv", header=TRUE)
target_data <- filter(target_data, (species == "protein1" | species == "protein2" | species == "protein3" | species == "protein4" | species == "protein5" | species == "protein6" | species == "protein7" | species == "protein8" | species == "protein9" | species == "protein10") & time != 301)

#Create line plot
target_line_plot <-  ggplot(target_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) + 
  geom_line(stat="identity", size=1) + 
  theme_cowplot() +
  scale_y_continuous(limits=c(0,40), expand=c(0,0)) +
  ylab('Transcript abundance') +
  xlab("Time (s)") +
  ggtitle("Target pattern") +
  theme(legend.position = "none",
        plot.title = element_text(size=10, face="bold"),
        axis.ticks.length = unit(2, "mm"),
        axis.text = element_text(size=8),
        axis.title = element_text(size=11)) +
  scale_color_manual(values=color_palette) +
  panel_border()

target_line_plot <- arrangeGrob(target_line_plot, top=textGrob("A", x = unit(0, "npc"), y=unit(1.0, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=10, fontfamily="Arial")))
```

Create simulated plot.

```{r, echo=FALSE}

setwd("../../figure_data/fig5/")

#Read in simulated tsv file an filter based on proteins
simulated_data <- read.table("expression_pattern_best.tsv", header=TRUE)
simulated_data <- filter(simulated_data, (species == "protein1" | species == "protein2" | species == "protein3" | species == "protein4" | species == "protein5" | species == "protein6" | species == "protein7" | species == "protein8" | species == "protein9" | species == "protein10") & time != 301)

#Create line plot
simulated_line_plot <-  ggplot(simulated_data, aes(fill=species, color=species, size=species, x=time, y=transcript)) + 
  geom_line(stat="identity", size=1) + 
  theme_cowplot() +
  scale_y_continuous(limits=c(0,40), expand=c(0,0)) +
  ylab('Transcript abundance') +
  xlab("Time (s)") +
  ggtitle("Evolved pattern") +
  theme(legend.position = "none",
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size=10, face="bold"),
        axis.ticks.length = unit(2, "mm"),
        axis.text = element_text(size=8),
        axis.title = element_text(size=11)) +
  scale_color_manual(values=color_palette) +
  panel_border()

simulated_line_plot <- arrangeGrob(simulated_line_plot, top=textGrob("A", x = unit(0, "npc"), y=unit(1.0, "npc"), just=c("left","top"), gp=gpar(col="white", font="bold", fontsize=10, fontfamily="Arial")))
```

Save figure 5.

```{r}

setwd("../../figure_output/figure5/")

#Read in genome architecture
img_starting <- readPNG("figure5_genome_arch_starting.png")
img_final <- readPNG("figure5_genome_arch_final.png")

img_starting <- arrangeGrob(rasterGrob(img_starting, vjust=-4.25), top=textGrob("B", x = unit(0, "npc"), y=unit(2.0, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=10, fontfamily="Arial")))
img_starting <- arrangeGrob(img_starting, top=textGrob("Starting architecture", x = unit(0.35, "npc"), y=unit(0, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=12, fontfamily="Arial")))

img_final <- arrangeGrob(rasterGrob(img_final, vjust=-12.25), top=textGrob("Final architecture", x = unit(0.37, "npc"), y=unit(8.0, "npc"), just=c("left","top"), gp=gpar(col="black", font="bold", fontsize=12, fontfamily="Arial")))

#Arrange plots
figure5 <- grid.arrange(target_line_plot, simulated_line_plot, img_starting, img_final, layout_matrix=rbind(c(1, 2), c(3), c(4)), widths=c(2.3, 2))

#Save as figure 5
ggsave("figure5.png", figure5, height=7, width=5, limitsize=FALSE, units="in")

```
